#ifndef bp_TA_insts_h
#define bp_TA_insts_h 1

// File Automatically Generated by MakeTA
// DO NOT EDIT


#include "ta_type.h"
#include "ta_TA_type.h"
#include "tamisc_TA_type.h"
#include "pdp_TA_type.h"
#include "bp.h"
#include "rbp.h"
#include "bp_TA_type.h"


extern	BpConSpec*	TAI_BpConSpec;
extern	BpCon*	TAI_BpCon;
extern	BpCon_Group*	TAI_BpCon_Group;
extern	BpUnit*	TAI_BpUnit;
extern	BpUnitSpec*	TAI_BpUnitSpec;
extern	BpTrial*	TAI_BpTrial;
extern	CE_Stat*	TAI_CE_Stat;
extern	NormDotProd_Stat*	TAI_NormDotProd_Stat;
extern	VecCor_Stat*	TAI_VecCor_Stat;
extern	NormVecLen_Stat*	TAI_NormVecLen_Stat;
extern	HebbBpConSpec*	TAI_HebbBpConSpec;
extern	ErrScaleBpConSpec*	TAI_ErrScaleBpConSpec;
extern	DeltaBarDeltaBpCon*	TAI_DeltaBarDeltaBpCon;
extern	DeltaBarDeltaBpConSpec*	TAI_DeltaBarDeltaBpConSpec;
extern	BpContextSpec*	TAI_BpContextSpec;
extern	LinearBpUnitSpec*	TAI_LinearBpUnitSpec;
extern	ThreshLinBpUnitSpec*	TAI_ThreshLinBpUnitSpec;
extern	NoisyBpUnitSpec*	TAI_NoisyBpUnitSpec;
extern	StochasticBpUnitSpec*	TAI_StochasticBpUnitSpec;
extern	RBFBpUnitSpec*	TAI_RBFBpUnitSpec;
extern	BumpBpUnitSpec*	TAI_BumpBpUnitSpec;
extern	ExpBpUnitSpec*	TAI_ExpBpUnitSpec;
extern	SoftMaxBpUnitSpec*	TAI_SoftMaxBpUnitSpec;
extern	RBpConSpec*	TAI_RBpConSpec;
extern	RBpUnit*	TAI_RBpUnit;
extern	RBpUnitSpec*	TAI_RBpUnitSpec;
extern	RBpTrial*	TAI_RBpTrial;
extern	RBpSequence*	TAI_RBpSequence;
extern	APBpCycle*	TAI_APBpCycle;
extern	APBpSettle*	TAI_APBpSettle;
extern	APBpTrial*	TAI_APBpTrial;
extern	APBpMaxDa_De*	TAI_APBpMaxDa_De;
extern	SymRBpConSpec*	TAI_SymRBpConSpec;
extern	float_CircBuffer*	TAI_float_CircBuffer;
extern	RBpSE_Stat*	TAI_RBpSE_Stat;
extern	RBpContextSpec*	TAI_RBpContextSpec;
extern	NoisyRBpUnitSpec*	TAI_NoisyRBpUnitSpec;
extern	BpWizard*	TAI_BpWizard;


#endif // bp_TA_insts_h
