// Copyright, 1995-2005, Regents of the University of Colorado,
// Carnegie Mellon University, Princeton University.
//
// This file is part of TA/PDP++
//
//   TA/PDP++ is free software; you can redistribute it and/or modify
//   it under the terms of the GNU General Public License as published by
//   the Free Software Foundation; either version 2 of the License, or
//   (at your option) any later version.
//
//   TA/PDP++ is distributed in the hope that it will be useful,
//   but WITHOUT ANY WARRANTY; without even the implied warranty of
//   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//   GNU General Public License for more details.


#ifndef bp_TA_types_h
#define bp_TA_types_h 1

// File Automatically Generated by MakeTA
// DO NOT EDIT


class TypeDef;
extern void ta_Init_bp();

extern TypeDef TA_BpConSpec;
extern TypeDef TA_BpCon;
extern TypeDef TA_BpCon_Group;
extern TypeDef TA_BpUnit;
extern TypeDef TA_BpUnitSpec;
extern TypeDef TA_BpTrial;
extern TypeDef TA_const_BpCon;
extern TypeDef TA_const_BpCon_ref;
extern TypeDef TA_BpConSpec_ptr;
extern TypeDef TA_BpCon_ptr;
extern TypeDef TA_BpUnit_ptr;
extern TypeDef TA_BpCon_Group_ptr;
extern TypeDef TA_const_BpConSpec;
extern TypeDef TA_const_BpConSpec_ref;
extern TypeDef TA_const_BpCon_Group;
extern TypeDef TA_const_BpCon_Group_ref;
extern TypeDef TA_BpUnitSpec_ptr;
extern TypeDef TA_const_BpUnitSpec;
extern TypeDef TA_const_BpUnitSpec_ref;
extern TypeDef TA_const_BpUnit;
extern TypeDef TA_const_BpUnit_ref;
extern TypeDef TA_const_BpTrial;
extern TypeDef TA_const_BpTrial_ref;
extern TypeDef TA_CE_Stat;
extern TypeDef TA_const_CE_Stat;
extern TypeDef TA_NormDotProd_Stat;
extern TypeDef TA_const_CE_Stat_ref;
extern TypeDef TA_const_NormDotProd_Stat;
extern TypeDef TA_const_NormDotProd_Stat_ref;
extern TypeDef TA_VecCor_Stat;
extern TypeDef TA_const_VecCor_Stat;
extern TypeDef TA_const_VecCor_Stat_ref;
extern TypeDef TA_NormVecLen_Stat;
extern TypeDef TA_const_NormVecLen_Stat;
extern TypeDef TA_const_NormVecLen_Stat_ref;
extern TypeDef TA_HebbBpConSpec;
extern TypeDef TA_const_HebbBpConSpec;
extern TypeDef TA_const_HebbBpConSpec_ref;
extern TypeDef TA_ErrScaleBpConSpec;
extern TypeDef TA_const_ErrScaleBpConSpec;
extern TypeDef TA_const_ErrScaleBpConSpec_ref;
extern TypeDef TA_DeltaBarDeltaBpCon;
extern TypeDef TA_DeltaBarDeltaBpCon_ptr;
extern TypeDef TA_const_DeltaBarDeltaBpCon;
extern TypeDef TA_const_DeltaBarDeltaBpCon_ref;
extern TypeDef TA_DeltaBarDeltaBpConSpec;
extern TypeDef TA_const_DeltaBarDeltaBpConSpec;
extern TypeDef TA_const_DeltaBarDeltaBpConSpec_ref;
extern TypeDef TA_BpContextSpec;
extern TypeDef TA_const_BpContextSpec;
extern TypeDef TA_LinearBpUnitSpec;
extern TypeDef TA_const_BpContextSpec_ref;
extern TypeDef TA_const_LinearBpUnitSpec;
extern TypeDef TA_const_LinearBpUnitSpec_ref;
extern TypeDef TA_ThreshLinBpUnitSpec;
extern TypeDef TA_const_ThreshLinBpUnitSpec;
extern TypeDef TA_const_ThreshLinBpUnitSpec_ref;
extern TypeDef TA_NoisyBpUnitSpec;
extern TypeDef TA_const_NoisyBpUnitSpec;
extern TypeDef TA_const_NoisyBpUnitSpec_ref;
extern TypeDef TA_StochasticBpUnitSpec;
extern TypeDef TA_const_StochasticBpUnitSpec;
extern TypeDef TA_const_StochasticBpUnitSpec_ref;
extern TypeDef TA_RBFBpUnitSpec;
extern TypeDef TA_const_RBFBpUnitSpec;
extern TypeDef TA_const_RBFBpUnitSpec_ref;
extern TypeDef TA_BumpBpUnitSpec;
extern TypeDef TA_const_BumpBpUnitSpec;
extern TypeDef TA_const_BumpBpUnitSpec_ref;
extern TypeDef TA_ExpBpUnitSpec;
extern TypeDef TA_const_ExpBpUnitSpec;
extern TypeDef TA_const_ExpBpUnitSpec_ref;
extern TypeDef TA_SoftMaxBpUnitSpec;
extern TypeDef TA_RBpConSpec;
extern TypeDef TA_const_SoftMaxBpUnitSpec;
extern TypeDef TA_RBpUnit;
extern TypeDef TA_const_SoftMaxBpUnitSpec_ref;
extern TypeDef TA_RBpUnitSpec;
extern TypeDef TA_RBpTrial;
extern TypeDef TA_RBpSequence;
extern TypeDef TA_APBpCycle;
extern TypeDef TA_APBpSettle;
extern TypeDef TA_APBpTrial;
extern TypeDef TA_APBpMaxDa_De;
extern TypeDef TA_RBpUnit_ptr;
extern TypeDef TA_const_RBpConSpec;
extern TypeDef TA_const_RBpConSpec_ref;
extern TypeDef TA_SymRBpConSpec;
extern TypeDef TA_const_RBpUnitSpec;
extern TypeDef TA_const_SymRBpConSpec;
extern TypeDef TA_const_RBpUnitSpec_ref;
extern TypeDef TA_const_SymRBpConSpec_ref;
extern TypeDef TA_float_CircBuffer;
extern TypeDef TA_const_RBpUnit;
extern TypeDef TA_const_float_CircBuffer;
extern TypeDef TA_const_RBpUnit_ref;
extern TypeDef TA_const_float_CircBuffer_ref;
extern TypeDef TA_const_RBpTrial;
extern TypeDef TA_const_RBpTrial_ref;
extern TypeDef TA_const_RBpSequence;
extern TypeDef TA_const_RBpSequence_ref;
extern TypeDef TA_RBpSE_Stat;
extern TypeDef TA_const_RBpSE_Stat;
extern TypeDef TA_RBpContextSpec;
extern TypeDef TA_const_RBpSE_Stat_ref;
extern TypeDef TA_APBpSettle_ptr;
extern TypeDef TA_const_RBpContextSpec;
extern TypeDef TA_APBpTrial_ptr;
extern TypeDef TA_const_RBpContextSpec_ref;
extern TypeDef TA_const_APBpCycle;
extern TypeDef TA_const_APBpCycle_ref;
extern TypeDef TA_const_APBpSettle;
extern TypeDef TA_const_APBpSettle_ref;
extern TypeDef TA_const_APBpTrial;
extern TypeDef TA_const_APBpTrial_ref;
extern TypeDef TA_const_APBpMaxDa_De;
extern TypeDef TA_const_APBpMaxDa_De_ref;
extern TypeDef TA_NoisyRBpUnitSpec;
extern TypeDef TA_const_NoisyRBpUnitSpec;
extern TypeDef TA_const_NoisyRBpUnitSpec_ref;
extern TypeDef TA_BpWizard;
extern TypeDef TA_const_BpWizard;
extern TypeDef TA_const_BpWizard_ref;


#endif // bp_TA_types_h
