#ifndef hw_TA_types_h
#define hw_TA_types_h 1

// File Automatically Generated by MakeTA
// DO NOT EDIT


class TypeDef;
extern void ta_Init_hw();

extern TypeDef TA_void;
extern TypeDef TA_char;
extern TypeDef TA_signed_char;
extern TypeDef TA_unsigned_char;
extern TypeDef TA_short;
extern TypeDef TA_signed_short;
extern TypeDef TA_short_int;
extern TypeDef TA_signed_short_int;
extern TypeDef TA_unsigned_short;
extern TypeDef TA_unsigned_short_int;
extern TypeDef TA_int;
extern TypeDef TA_signed_int;
extern TypeDef TA_signed;
extern TypeDef TA_unsigned_int;
extern TypeDef TA_unsigned;
extern TypeDef TA_int64_t;
extern TypeDef TA_long_long;
extern TypeDef TA_signed_long_long;
extern TypeDef TA_uint64_t;
extern TypeDef TA_unsigned_long_long;
extern TypeDef TA_long;
extern TypeDef TA_signed_long;
extern TypeDef TA_long_int;
extern TypeDef TA_signed_long_int;
extern TypeDef TA_unsigned_long;
extern TypeDef TA_unsigned_long_int;
extern TypeDef TA_intptr_t;
extern TypeDef TA_uintptr_t;
extern TypeDef TA_float;
extern TypeDef TA_double;
extern TypeDef TA_bool;
extern TypeDef TA_const;
extern TypeDef TA_enum;
extern TypeDef TA_struct;
extern TypeDef TA_union;
extern TypeDef TA_class;
extern TypeDef TA_template;
extern TypeDef TA_templ_inst;
extern TypeDef TA_ta_array;
extern TypeDef TA_taBase;
extern TypeDef TA_taRegFun;
extern TypeDef TA_TypeDef;
extern TypeDef TA_MemberDef;
extern TypeDef TA_MethodDef;
extern TypeDef TA_taString;
extern TypeDef TA_Variant;
extern TypeDef TA_void_ptr;
extern TypeDef TA_HelloPlugin;
extern TypeDef TA_const_taString_ref;
extern TypeDef TA_const_taString;
extern TypeDef TA_taStrRep_ptr;
extern TypeDef TA_taStrRep;
extern TypeDef TA_const_char_ptr;
extern TypeDef TA_const_char;
extern TypeDef TA_char_ptr;
extern TypeDef TA_uint;
extern TypeDef TA_bool_ptr;
extern TypeDef TA_ushort;
extern TypeDef TA_taString_ref;
extern TypeDef TA_const_void_ptr;
extern TypeDef TA_const_void;
extern TypeDef TA_ostream_ref;
extern TypeDef TA_ostream;
extern TypeDef TA_istream_ref;
extern TypeDef TA_istream;
extern TypeDef TA_const_Variant_ref;
extern TypeDef TA_const_Variant;
extern TypeDef TA_byte;
extern TypeDef TA_taBase_ptr;
extern TypeDef TA_taMatrix_ptr;
extern TypeDef TA_taMatrix;
extern TypeDef TA_const_taBase_ptr;
extern TypeDef TA_const_taBase;
extern TypeDef TA_const_taMatrix_ptr;
extern TypeDef TA_const_taMatrix;
extern TypeDef TA_const_QVariant_ref;
extern TypeDef TA_const_QVariant;
extern TypeDef TA_QVariant;
extern TypeDef TA_TypeDef_ptr_ref;
extern TypeDef TA_TypeDef_ptr;
extern TypeDef TA_void_ptr_ref;
extern TypeDef TA_int_ref;
extern TypeDef TA_QObject;
extern TypeDef TA_IPlugin;


#endif // hw_TA_types_h
