#ifndef ta_TA_insts_h
#define ta_TA_insts_h 1

// File Automatically Generated by MakeTA
// DO NOT EDIT


#include "ta_type.h"
#include "igeometry.h"
#include "ta_def.h"
#include "ta_platform.h"
#include "ta_thread.h"
#include "ta_string.h"
#include "ta_stdef.h"
#include "ta_variant.h"
#include "ifont.h"
#include "ta_mtrnd.h"
#include "ta_list.h"
#include "ta_filer.h"
#include "icolor.h"
#include "ta_type.h"
#include "ta_base.h"
#include "ta_TA_type.h"


extern taBase*	TAI_taBase;
extern iPoint*	TAI_iPoint;
extern iVec3i*	TAI_iVec3i;
extern iSize*	TAI_iSize;
extern iRect*	TAI_iRect;
extern iVec3f*	TAI_iVec3f;
extern iBox3f*	TAI_iBox3f;
extern taPtrList<taHashEl>*	TAI_taPtrList_taHashEl_;
extern taPtrList<taHashBucket>*	TAI_taPtrList_taHashBucket_;
extern taDataLinkItr*	TAI_taDataLinkItr;
extern taBase**	TAI_TAPtr;
extern taPlainArray<taString>*	TAI_taPlainArray_taString_;
extern taPlainArray<int>*	TAI_taPlainArray_int_;
extern taPlainArray<NameVar>*	TAI_taPlainArray_NameVar_;
extern taPtrList<DumpFileCvt>*	TAI_taPtrList_DumpFileCvt_;
extern UserDataItemBase*	TAI_UserDataItemBase;
extern taMisc*	TAI_taMisc;
extern taPtrList<EnumDef>*	TAI_taPtrList_EnumDef_;
extern EnumSpace*	TAI_EnumSpace;
extern taPtrList<void>*	TAI_taPtrList_void_;
extern TokenSpace*	TAI_TokenSpace;
extern taPtrList<MemberDef>*	TAI_taPtrList_MemberDef_;
extern Member_List*	TAI_Member_List;
extern MemberSpace*	TAI_MemberSpace;
extern taPtrList<MethodDef>*	TAI_taPtrList_MethodDef_;
extern Method_List*	TAI_Method_List;
extern MethodSpace*	TAI_MethodSpace;
extern taPtrList<TypeDef>*	TAI_taPtrList_TypeDef_;
extern TypeSpace*	TAI_TypeSpace;
extern TypeItem*	TAI_TypeItem;
extern EnumDef*	TAI_EnumDef;
extern taOBase*	TAI_taOBase;
extern taOABase*	TAI_taOABase;
extern taDataView*	TAI_taDataView;
extern taNBase*	TAI_taNBase;
extern UserDataItem*	TAI_UserDataItem;
extern tabMisc*	TAI_tabMisc;
extern taNBase**	TAI_TANPtr;
extern taFBase*	TAI_taFBase;
extern taPtrList<taBase>*	TAI_taPtrList_taBase_;
extern taPtrList_base<taBase>*	TAI_taPtrList_base_taBase_;
extern taList_impl*	TAI_taList_impl;
extern taList<taBase>*	TAI_taList_taBase_;
extern taBase_List*	TAI_taBase_List;
extern taList<taDataView>*	TAI_taList_taDataView_;
extern DataView_List*	TAI_DataView_List;
extern taArray_base*	TAI_taArray_base;
extern taArray<int>*	TAI_taArray_int_;
extern int_Array*	TAI_int_Array;
extern taArray<float>*	TAI_taArray_float_;
extern float_Array*	TAI_float_Array;
extern taArray<double>*	TAI_taArray_double_;
extern double_Array*	TAI_double_Array;
extern taArray<char>*	TAI_taArray_char_;
extern char_Array*	TAI_char_Array;
extern taArray<taString>*	TAI_taArray_taString_;
extern String_Array*	TAI_String_Array;
extern SArg_Array*	TAI_SArg_Array;
extern taArray<Variant>*	TAI_taArray_Variant_;
extern Variant_Array*	TAI_Variant_Array;
extern taArray<void*>*	TAI_taArray_voidptr_;
extern voidptr_Array*	TAI_voidptr_Array;
extern taList<UserDataItemBase>*	TAI_taList_UserDataItemBase_;
extern UserDataItem_List*	TAI_UserDataItem_List;


#endif // ta_TA_insts_h
