// Copyright (C) 1995-2005 Regents of the University of Colorado,
// Carnegie Mellon University, Princeton University.
// 
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
// 
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
#ifndef tamisc_TA_insts_h
#define tamisc_TA_insts_h 1

// File Automatically Generated by MakeTA
// DO NOT EDIT


#include "ta_type.h"
#include "ta_TA_type.h"
#include "fontspec.h"
#include "xform.h"
#include "tarandom.h"
#include "tdgeometry.h"
#include "aggregate.h"
#include "minmax.h"
#include "ta_data_defs.h"
#include "ta_data.h"
#include "colorscale.h"
#include "datatable.h"
#include "datagraph.h"
#include "fun_lookup.h"
#include "colorbar_qt.h"
#include "safeptr_so.h"
#include "t3node_so.h"
#include "t3viewer.h"
#include "colorbar_so.h"
#include "datatable_qtso.h"
#include "datagraph_so.h"
#include "datagraph_qtso.h"
#include "tamisc_maketa_defs.h"
#include "tamisc_stdef.h"
#include "tamisc_TA_type.h"


extern	FontSpec*	TAI_FontSpec;
extern	ViewLabel*	TAI_ViewLabel;
extern	taList<ViewLabel>*	TAI_taList_ViewLabel_;
extern	ViewLabel_List*	TAI_ViewLabel_List;
extern	taList<Xform>*	TAI_taList_Xform_;
extern	Xform_List*	TAI_Xform_List;
extern	RndSeed*	TAI_RndSeed;
extern	Random*	TAI_Random;
extern	TimeUsed*	TAI_TimeUsed;
extern	TwoDCoord*	TAI_TwoDCoord;
extern	PosTwoDCoord*	TAI_PosTwoDCoord;
extern	TDCoord*	TAI_TDCoord;
extern	PosTDCoord*	TAI_PosTDCoord;
extern	FloatTwoDCoord*	TAI_FloatTwoDCoord;
extern	FloatTDCoord*	TAI_FloatTDCoord;
extern	FloatRotation*	TAI_FloatRotation;
extern	FloatTransform*	TAI_FloatTransform;
extern	ValIdx*	TAI_ValIdx;
extern	CountParam*	TAI_CountParam;
extern	Aggregate*	TAI_Aggregate;
extern	SimpleMathSpec*	TAI_SimpleMathSpec;
extern	MinMax*	TAI_MinMax;
extern	MinMaxRange*	TAI_MinMaxRange;
extern	FixedMinMax*	TAI_FixedMinMax;
extern	Modulo*	TAI_Modulo;
extern	MinMaxInt*	TAI_MinMaxInt;
extern	DataTransferMode*	TAI_DataTransferMode;
extern	taMatrix_impl**	TAI_ptaMatrix_impl;
extern	DataConnector*	TAI_DataConnector;
extern	SinkChannel*	TAI_SinkChannel;
extern	SourceChannel*	TAI_SourceChannel;
extern	taList<DataConnector>*	TAI_taList_DataConnector_;
extern	DataConnector_List*	TAI_DataConnector_List;
extern	taList<SourceChannel>*	TAI_taList_SourceChannel_;
extern	SourceChannel_List*	TAI_SourceChannel_List;
extern	taList<SinkChannel>*	TAI_taList_SinkChannel_;
extern	SinkChannel_List*	TAI_SinkChannel_List;
extern	RGBA*	TAI_RGBA;
extern	TAColor*	TAI_TAColor;
extern	ColorScaleSpec*	TAI_ColorScaleSpec;
extern	ScaleRange*	TAI_ScaleRange;
extern	ColorScale*	TAI_ColorScale;
extern	taList<RGBA>*	TAI_taList_RGBA_;
extern	RGBA_List*	TAI_RGBA_List;
extern	taList<TAColor>*	TAI_taList_TAColor_;
extern	TAColor_List*	TAI_TAColor_List;
extern	taGroup<ColorScaleSpec>*	TAI_taGroup_ColorScaleSpec_;
extern	ColorScaleSpec_MGroup*	TAI_ColorScaleSpec_MGroup;
extern	taList<ScaleRange>*	TAI_taList_ScaleRange_;
extern	ScaleRange_List*	TAI_ScaleRange_List;
extern	ClustNode*	TAI_ClustNode;
extern	DataItem*	TAI_DataItem;
extern	taList<DataItem>*	TAI_taList_DataItem_;
extern	DataItem_List*	TAI_DataItem_List;
extern	LogData*	TAI_LogData;
extern	DataArray_impl*	TAI_DataArray_impl;
extern	taGroup<DataArray_impl>*	TAI_taGroup_DataArray_impl_;
extern	DataTable*	TAI_DataTable;
extern	DataArray<float_RArray>*	TAI_DataArray_float_RArray_;
extern	float_Data*	TAI_float_Data;
extern	DataArray<DString_Array>*	TAI_DataArray_DString_Array_;
extern	String_Data*	TAI_String_Data;
extern	ClustLink*	TAI_ClustLink;
extern	DA_ViewSpec*	TAI_DA_ViewSpec;
extern	taGroup<DA_ViewSpec>*	TAI_taGroup_DA_ViewSpec_;
extern	DT_ViewSpec*	TAI_DT_ViewSpec;
extern	DA_TextViewSpec*	TAI_DA_TextViewSpec;
extern	DA_NetViewSpec*	TAI_DA_NetViewSpec;
extern	DA_GridViewSpec*	TAI_DA_GridViewSpec;
extern	DT_GridViewSpec*	TAI_DT_GridViewSpec;
extern	GraphColSpec*	TAI_GraphColSpec;
extern	XAxisSpec*	TAI_XAxisSpec;
extern	YAxisSpec*	TAI_YAxisSpec;
extern	ZAxisSpec*	TAI_ZAxisSpec;
extern	GraphSpec*	TAI_GraphSpec;
extern	taList<YAxisSpec>*	TAI_taList_YAxisSpec_;
extern	YAxisSpec_List*	TAI_YAxisSpec_List;
extern	GraphletSpec*	TAI_GraphletSpec;
extern	taList<GraphletSpec>*	TAI_taList_GraphletSpec_;
extern	GraphletSpec_List*	TAI_GraphletSpec_List;
extern	FunLookupND*	TAI_FunLookupND;
extern	T3DataView*	TAI_T3DataView;
extern	T3DataViewPar*	TAI_T3DataViewPar;
extern	T3DataViewRoot*	TAI_T3DataViewRoot;
extern	iT3ViewspaceWidget*	TAI_iT3ViewspaceWidget;
extern	T3DataViewer*	TAI_T3DataViewer;
extern	taList<T3DataView>*	TAI_taList_T3DataView_;
extern	T3DataView_List*	TAI_T3DataView_List;
extern	taPtrList<T3DataView>*	TAI_taPtrList_T3DataView_;
extern	T3DataView_PtrList*	TAI_T3DataView_PtrList;
extern	tabDataTableViewType*	TAI_tabDataTableViewType;
extern	AxisView*	TAI_AxisView;
extern	GraphLine*	TAI_GraphLine;
extern	GraphView*	TAI_GraphView;
extern	GraphViews*	TAI_GraphViews;


#endif // tamisc_TA_insts_h
