#ifndef test_TA_types_h
#define test_TA_types_h 1

// File Automatically Generated by MakeTA
// DO NOT EDIT


class TypeDef;
extern void ta_Init_test();

extern TypeDef TA_void;
extern TypeDef TA_int;
extern TypeDef TA_short;
extern TypeDef TA_long;
extern TypeDef TA_char;
extern TypeDef TA_unsigned;
extern TypeDef TA_signed;
extern TypeDef TA_float;
extern TypeDef TA_double;
extern TypeDef TA_bool;
extern TypeDef TA_const;
extern TypeDef TA_enum;
extern TypeDef TA_struct;
extern TypeDef TA_union;
extern TypeDef TA_class;
extern TypeDef TA_template;
extern TypeDef TA_templ_inst;
extern TypeDef TA_ta_array;
extern TypeDef TA_taBase;
extern TypeDef TA_taRegFun;
extern TypeDef TA_TypeDef;
extern TypeDef TA_MemberDef;
extern TypeDef TA_MethodDef;
extern TypeDef TA_taString;
extern TypeDef TA_void_ptr;
extern TypeDef TA_MyClass;
extern TypeDef TA_MySubClass;
extern TypeDef TA_MyTemplate;
extern TypeDef TA_MyTemplate_MyClass_;
extern TypeDef TA_MyTemplate_MyClass;


#endif // test_TA_types_h
