// File Automatically Generated by MakeTA
// DO NOT EDIT


#include "ta_type.h"
#include "ta_type_constr.h"
#include "css_basic_types.h"
#include "css_c_ptr_types.h"
#include "ta_css.h"
#include "test.h"
#include "test_TA_type.h"
#include "test_TA_inst.h"


// Types

TypeDef TA_void("void", 1, 0, 0, 0,1);
TypeDef TA_int("int", 1, 0, 0, 0,1);
TypeDef TA_short("short", 1, 0, 0, 0,1);
TypeDef TA_long("long", 1, 0, 0, 0,1);
TypeDef TA_char("char", 1, 0, 0, 0,1);
TypeDef TA_unsigned("unsigned", 1, 0, 0, 0,1);
TypeDef TA_signed("signed", 1, 0, 0, 0,1);
TypeDef TA_float("float", 1, 0, 0, 0,1);
TypeDef TA_double("double", 1, 0, 0, 0,1);
TypeDef TA_bool("bool", 1, 0, 0, 0,1);
TypeDef TA_const("const", 1, 0, 0, 0,1);
TypeDef TA_enum("enum", 1, 0, 0, 1,1);
TypeDef TA_struct("struct", 1, 0, 0, 1,1);
TypeDef TA_union("union", 1, 0, 0, 1,1);
TypeDef TA_class("class", 1, 0, 0, 1,1);
TypeDef TA_template("template", 1, 0, 0, 1,1);
TypeDef TA_templ_inst("templ_inst", 1, 0, 0, 1,1);
TypeDef TA_ta_array("ta_array", 1, 0, 0, 1,1);
TypeDef TA_taBase("taBase", " Base type for all type-aware classes", 
	"", "", "", sizeof(taBase), (void**)0, 0, 0, 0,1);
TypeDef TA_taRegFun("taRegFun", 1, 0, 0, 0,1);
TypeDef TA_TypeDef("TypeDef", 1, 0, 0, 0,1);
TypeDef TA_MemberDef("MemberDef", 1, 0, 0, 0,1);
TypeDef TA_MethodDef("MethodDef", 1, 0, 0, 0,1);
TypeDef TA_taString("taString", "", 
	"", "", "", sizeof(taString), (void**)0, 0, 0, 0,1);
TypeDef TA_void_ptr("void_ptr", 1, 1, 0, 1,1);
TypeDef TA_MyClass("MyClass", "", 
	"", "", "", sizeof(MyClass), (void**)0, 1, 0, 0,1);
TypeDef TA_MySubClass("MySubClass", "", 
	"", "", "", sizeof(MySubClass), (void**)0, 1, 0, 0,1);
TypeDef TA_MyTemplate("MyTemplate", 1, 0, 0, 0,1);
TypeDef TA_MyTemplate_MyClass_("MyTemplate_MyClass_", "", 
	"", "", "", sizeof(MyTemplate<MyClass>), (void**)0, 0, 0, 0,1);
TypeDef TA_MyTemplate_MyClass("MyTemplate_MyClass", "", 
	"", "", "", sizeof(MyTemplate_MyClass), (void**)0, 1, 0, 0,1);

// Instances

  static cssEl* cssElCFun_MyTemplate_MyClass__setVar_stub(void* ths,int, cssEl** arg) {
    cssEl* rval=&cssMisc::Void;
    ((MyTemplate<MyClass>*)ths)->setVar(*(MyClass*)arg[1]->GetVoidPtrOfType(&TA_MyClass));
    return rval;}
  static cssEl* cssElCFun_MyTemplate_MyClass__Set_stub(void* ths,int, cssEl** arg) {
    cssEl* rval=&cssMisc::Void;
    ((MyTemplate<MyClass>*)ths)->Set((int)*arg[1], *(MyClass*)arg[2]->GetVoidPtrOfType(&TA_MyClass));
    return rval;}

// Type Data

static int MyTemplate<MyClass>::* TA_MyTemplate_MyClass__MbrOff;
static MemberDef_data TA_MyTemplate_MyClass__MemberDef[]={
  {&TA_MyClass,NULL,"myVar","","","",
    *((ta_memb_ptr*)&(TA_MyTemplate_MyClass__MbrOff=(int MyTemplate<MyClass>::*)(&MyTemplate<MyClass>::myVar))),0,NULL,0},
  NULL};
static MethodArgs_data TA_MyTemplate_MyClass__setVar_MethArgs[]={
  {NULL,"::const_MyClass_ref","val",""},
  NULL};
static MethodArgs_data TA_MyTemplate_MyClass__Set_MethArgs[]={
  {&TA_int,NULL,"i",""},
  {NULL,"::const_MyClass_ref","item",""},
  NULL};
static MethodDef_data TA_MyTemplate_MyClass__MethodDef[]={
  {&TA_void,NULL,"setVar","","","",
    0,1,-1,0,NULL,cssElCFun_MyTemplate_MyClass__setVar_stub,TA_MyTemplate_MyClass__setVar_MethArgs},
  {&TA_void,NULL,"Set","","","",
    0,2,-1,0,NULL,cssElCFun_MyTemplate_MyClass__Set_stub,TA_MyTemplate_MyClass__Set_MethArgs},
  NULL};

// Init Function


static bool ta_Init_test_done = false;

void ta_Init_test() {
  TypeDef* sbt;

  if(ta_Init_test_done) return;
  ta_Init_test_done = true;


  taMisc::in_init = true;

  taMisc::types.Add(&TA_void);
  taMisc::types.Add(&TA_int);
  taMisc::types.Add(&TA_short);
  taMisc::types.Add(&TA_long);
  taMisc::types.Add(&TA_char);
  taMisc::types.Add(&TA_unsigned);
  taMisc::types.Add(&TA_signed);
  taMisc::types.Add(&TA_float);
  taMisc::types.Add(&TA_double);
  taMisc::types.Add(&TA_bool);
  taMisc::types.Add(&TA_const);
  taMisc::types.Add(&TA_enum);
  taMisc::types.Add(&TA_struct);
  taMisc::types.Add(&TA_union);
  taMisc::types.Add(&TA_class);
  taMisc::types.Add(&TA_template);
  taMisc::types.Add(&TA_templ_inst);
  taMisc::types.Add(&TA_ta_array);
  taMisc::types.Add(&TA_taBase);
    TA_taBase.AddParFormal(&TA_class);
  taMisc::types.Add(&TA_TypeDef);
  taMisc::types.Add(&TA_MemberDef);
  taMisc::types.Add(&TA_MethodDef);
  taMisc::types.Add(&TA_taString);
    TA_taString.AddParFormal(&TA_class);
  taMisc::types.Add(&TA_void_ptr);
    TA_void_ptr.AddParents(&TA_void);
  taMisc::types.Add(&TA_MyClass);
    TA_MyClass.AddParFormal(&TA_class);
  taMisc::types.Add(&TA_MySubClass);
    TA_MySubClass.AddParFormal(&TA_class);
    TA_MySubClass.AddClassPar(&TA_MyClass,0);
  taMisc::types.Add(&TA_MyTemplate);
    TA_MyTemplate.AddParFormal(&TA_class, &TA_template);
  taMisc::types.Add(&TA_MyTemplate_MyClass_);
    TA_MyTemplate_MyClass_.AddParFormal(&TA_class, &TA_templ_inst);
    TA_MyTemplate_MyClass_.AddClassPar(&TA_MyTemplate,0);
    sbt = new TypeDef("const_MyClass", 1, 0, 0);
    sbt->AddParents(&TA_const, &TA_MyClass);
    TA_MyTemplate_MyClass_.sub_types.Add(sbt);
    sbt = new TypeDef("const_MyClass_ref", 1, 0, 1);
    sbt->AddParents(TA_MyTemplate_MyClass_.sub_types.FindName("const_MyClass"));
    TA_MyTemplate_MyClass_.sub_types.Add(sbt);
    tac_AddMembers(TA_MyTemplate_MyClass_,TA_MyTemplate_MyClass__MemberDef);
    tac_AddMethods(TA_MyTemplate_MyClass_,TA_MyTemplate_MyClass__MethodDef);
  taMisc::types.Add(&TA_MyTemplate_MyClass);
    TA_MyTemplate_MyClass.AddParFormal(&TA_class);
    TA_MyTemplate_MyClass.AddClassPar(&TA_MyTemplate_MyClass_,0);


  taMisc::in_init = false;
} 
