# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "/Applications/CMake 2.8-8.app/Contents/bin/cmake"

# The command to remove a file.
RM = "/Applications/CMake 2.8-8.app/Contents/bin/cmake" -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = "/Applications/CMake 2.8-8.app/Contents/bin/ccmake"

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/thazy/emergent

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/thazy/emergent

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"/Applications/CMake 2.8-8.app/Contents/bin/ccmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	"/Applications/CMake 2.8-8.app/Contents/bin/cmake" -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	"/Applications/CMake 2.8-8.app/Contents/bin/cmake" -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	"/Applications/CMake 2.8-8.app/Contents/bin/cmake" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	"/Applications/CMake 2.8-8.app/Contents/bin/cmake" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	"/Applications/CMake 2.8-8.app/Contents/bin/cpack" --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	"/Applications/CMake 2.8-8.app/Contents/bin/cpack" --config ./CPackSourceConfig.cmake /Users/thazy/emergent/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"/Applications/CMake 2.8-8.app/Contents/bin/cmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	"/Applications/CMake 2.8-8.app/Contents/bin/ctest" --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/thazy/emergent/CMakeFiles /Users/thazy/emergent/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/thazy/emergent/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ChangeLog

# Build rule for target.
ChangeLog: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ChangeLog
.PHONY : ChangeLog

# fast build rule for target.
ChangeLog/fast:
	$(MAKE) -f CMakeFiles/ChangeLog.dir/build.make CMakeFiles/ChangeLog.dir/build
.PHONY : ChangeLog/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) -f CMakeFiles/Continuous.dir/build.make CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) -f CMakeFiles/ContinuousBuild.dir/build.make CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) -f CMakeFiles/ContinuousConfigure.dir/build.make CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) -f CMakeFiles/ContinuousCoverage.dir/build.make CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) -f CMakeFiles/ContinuousMemCheck.dir/build.make CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) -f CMakeFiles/ContinuousStart.dir/build.make CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) -f CMakeFiles/ContinuousSubmit.dir/build.make CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) -f CMakeFiles/ContinuousTest.dir/build.make CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) -f CMakeFiles/ContinuousUpdate.dir/build.make CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) -f CMakeFiles/Experimental.dir/build.make CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) -f CMakeFiles/ExperimentalBuild.dir/build.make CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) -f CMakeFiles/ExperimentalConfigure.dir/build.make CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) -f CMakeFiles/ExperimentalCoverage.dir/build.make CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) -f CMakeFiles/ExperimentalMemCheck.dir/build.make CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) -f CMakeFiles/ExperimentalStart.dir/build.make CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) -f CMakeFiles/ExperimentalSubmit.dir/build.make CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) -f CMakeFiles/ExperimentalTest.dir/build.make CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) -f CMakeFiles/ExperimentalUpdate.dir/build.make CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) -f CMakeFiles/Nightly.dir/build.make CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) -f CMakeFiles/NightlyBuild.dir/build.make CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) -f CMakeFiles/NightlyConfigure.dir/build.make CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) -f CMakeFiles/NightlyCoverage.dir/build.make CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) -f CMakeFiles/NightlyMemCheck.dir/build.make CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) -f CMakeFiles/NightlyMemoryCheck.dir/build.make CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) -f CMakeFiles/NightlyStart.dir/build.make CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) -f CMakeFiles/NightlySubmit.dir/build.make CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) -f CMakeFiles/NightlyTest.dir/build.make CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) -f CMakeFiles/NightlyUpdate.dir/build.make CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named clean_plugins

# Build rule for target.
clean_plugins: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clean_plugins
.PHONY : clean_plugins

# fast build rule for target.
clean_plugins/fast:
	$(MAKE) -f CMakeFiles/clean_plugins.dir/build.make CMakeFiles/clean_plugins.dir/build
.PHONY : clean_plugins/fast

#=============================================================================
# Target rules for targets named clean_system_plugins

# Build rule for target.
clean_system_plugins: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clean_system_plugins
.PHONY : clean_system_plugins

# fast build rule for target.
clean_system_plugins/fast:
	$(MAKE) -f CMakeFiles/clean_system_plugins.dir/build.make CMakeFiles/clean_system_plugins.dir/build
.PHONY : clean_system_plugins/fast

#=============================================================================
# Target rules for targets named clean_ta_all

# Build rule for target.
clean_ta_all: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clean_ta_all
.PHONY : clean_ta_all

# fast build rule for target.
clean_ta_all/fast:
	$(MAKE) -f CMakeFiles/clean_ta_all.dir/build.make CMakeFiles/clean_ta_all.dir/build
.PHONY : clean_ta_all/fast

#=============================================================================
# Target rules for targets named clean_ta_emergent

# Build rule for target.
clean_ta_emergent: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clean_ta_emergent
.PHONY : clean_ta_emergent

# fast build rule for target.
clean_ta_emergent/fast:
	$(MAKE) -f CMakeFiles/clean_ta_emergent.dir/build.make CMakeFiles/clean_ta_emergent.dir/build
.PHONY : clean_ta_emergent/fast

#=============================================================================
# Target rules for targets named clean_user_plugins

# Build rule for target.
clean_user_plugins: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clean_user_plugins
.PHONY : clean_user_plugins

# fast build rule for target.
clean_user_plugins/fast:
	$(MAKE) -f CMakeFiles/clean_user_plugins.dir/build.make CMakeFiles/clean_user_plugins.dir/build
.PHONY : clean_user_plugins/fast

#=============================================================================
# Target rules for targets named plugins

# Build rule for target.
plugins: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 plugins
.PHONY : plugins

# fast build rule for target.
plugins/fast:
	$(MAKE) -f CMakeFiles/plugins.dir/build.make CMakeFiles/plugins.dir/build
.PHONY : plugins/fast

#=============================================================================
# Target rules for targets named svn_commit

# Build rule for target.
svn_commit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 svn_commit
.PHONY : svn_commit

# fast build rule for target.
svn_commit/fast:
	$(MAKE) -f CMakeFiles/svn_commit.dir/build.make CMakeFiles/svn_commit.dir/build
.PHONY : svn_commit/fast

#=============================================================================
# Target rules for targets named svn_update

# Build rule for target.
svn_update: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 svn_update
.PHONY : svn_update

# fast build rule for target.
svn_update/fast:
	$(MAKE) -f CMakeFiles/svn_update.dir/build.make CMakeFiles/svn_update.dir/build
.PHONY : svn_update/fast

#=============================================================================
# Target rules for targets named system_plugins

# Build rule for target.
system_plugins: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 system_plugins
.PHONY : system_plugins

# fast build rule for target.
system_plugins/fast:
	$(MAKE) -f CMakeFiles/system_plugins.dir/build.make CMakeFiles/system_plugins.dir/build
.PHONY : system_plugins/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named user_plugins

# Build rule for target.
user_plugins: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 user_plugins
.PHONY : user_plugins

# fast build rule for target.
user_plugins/fast:
	$(MAKE) -f CMakeFiles/user_plugins.dir/build.make CMakeFiles/user_plugins.dir/build
.PHONY : user_plugins/fast

#=============================================================================
# Target rules for targets named make_mta_parse

# Build rule for target.
make_mta_parse: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 make_mta_parse
.PHONY : make_mta_parse

# fast build rule for target.
make_mta_parse/fast:
	$(MAKE) -f src/temt/maketa/CMakeFiles/make_mta_parse.dir/build.make src/temt/maketa/CMakeFiles/make_mta_parse.dir/build
.PHONY : make_mta_parse/fast

#=============================================================================
# Target rules for targets named maketa

# Build rule for target.
maketa: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 maketa
.PHONY : maketa

# fast build rule for target.
maketa/fast:
	$(MAKE) -f src/temt/maketa/CMakeFiles/maketa.dir/build.make src/temt/maketa/CMakeFiles/maketa.dir/build
.PHONY : maketa/fast

#=============================================================================
# Target rules for targets named make_ta_qrc

# Build rule for target.
make_ta_qrc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 make_ta_qrc
.PHONY : make_ta_qrc

# fast build rule for target.
make_ta_qrc/fast:
	$(MAKE) -f src/temt/ta/CMakeFiles/make_ta_qrc.dir/build.make src/temt/ta/CMakeFiles/make_ta_qrc.dir/build
.PHONY : make_ta_qrc/fast

#=============================================================================
# Target rules for targets named make_css_parse

# Build rule for target.
make_css_parse: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 make_css_parse
.PHONY : make_css_parse

# fast build rule for target.
make_css_parse/fast:
	$(MAKE) -f src/temt/css/CMakeFiles/make_css_parse.dir/build.make src/temt/css/CMakeFiles/make_css_parse.dir/build
.PHONY : make_css_parse/fast

#=============================================================================
# Target rules for targets named clean_ta_ta

# Build rule for target.
clean_ta_ta: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clean_ta_ta
.PHONY : clean_ta_ta

# fast build rule for target.
clean_ta_ta/fast:
	$(MAKE) -f src/temt/lib/CMakeFiles/clean_ta_ta.dir/build.make src/temt/lib/CMakeFiles/clean_ta_ta.dir/build
.PHONY : clean_ta_ta/fast

#=============================================================================
# Target rules for targets named svn_revision_header

# Build rule for target.
svn_revision_header: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 svn_revision_header
.PHONY : svn_revision_header

# fast build rule for target.
svn_revision_header/fast:
	$(MAKE) -f src/temt/lib/CMakeFiles/svn_revision_header.dir/build.make src/temt/lib/CMakeFiles/svn_revision_header.dir/build
.PHONY : svn_revision_header/fast

#=============================================================================
# Target rules for targets named temt

# Build rule for target.
temt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 temt
.PHONY : temt

# fast build rule for target.
temt/fast:
	$(MAKE) -f src/temt/lib/CMakeFiles/temt.dir/build.make src/temt/lib/CMakeFiles/temt.dir/build
.PHONY : temt/fast

#=============================================================================
# Target rules for targets named css

# Build rule for target.
css: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 css
.PHONY : css

# fast build rule for target.
css/fast:
	$(MAKE) -f src/temt/css_bin/CMakeFiles/css.dir/build.make src/temt/css_bin/CMakeFiles/css.dir/build
.PHONY : css/fast

#=============================================================================
# Target rules for targets named make_actr_parse

# Build rule for target.
make_actr_parse: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 make_actr_parse
.PHONY : make_actr_parse

# fast build rule for target.
make_actr_parse/fast:
	$(MAKE) -f src/emergent/actr/CMakeFiles/make_actr_parse.dir/build.make src/emergent/actr/CMakeFiles/make_actr_parse.dir/build
.PHONY : make_actr_parse/fast

#=============================================================================
# Target rules for targets named clean_ta_actr

# Build rule for target.
clean_ta_actr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clean_ta_actr
.PHONY : clean_ta_actr

# fast build rule for target.
clean_ta_actr/fast:
	$(MAKE) -f src/emergent/lib/CMakeFiles/clean_ta_actr.dir/build.make src/emergent/lib/CMakeFiles/clean_ta_actr.dir/build
.PHONY : clean_ta_actr/fast

#=============================================================================
# Target rules for targets named clean_ta_bp

# Build rule for target.
clean_ta_bp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clean_ta_bp
.PHONY : clean_ta_bp

# fast build rule for target.
clean_ta_bp/fast:
	$(MAKE) -f src/emergent/lib/CMakeFiles/clean_ta_bp.dir/build.make src/emergent/lib/CMakeFiles/clean_ta_bp.dir/build
.PHONY : clean_ta_bp/fast

#=============================================================================
# Target rules for targets named clean_ta_cs

# Build rule for target.
clean_ta_cs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clean_ta_cs
.PHONY : clean_ta_cs

# fast build rule for target.
clean_ta_cs/fast:
	$(MAKE) -f src/emergent/lib/CMakeFiles/clean_ta_cs.dir/build.make src/emergent/lib/CMakeFiles/clean_ta_cs.dir/build
.PHONY : clean_ta_cs/fast

#=============================================================================
# Target rules for targets named clean_ta_leabra

# Build rule for target.
clean_ta_leabra: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clean_ta_leabra
.PHONY : clean_ta_leabra

# fast build rule for target.
clean_ta_leabra/fast:
	$(MAKE) -f src/emergent/lib/CMakeFiles/clean_ta_leabra.dir/build.make src/emergent/lib/CMakeFiles/clean_ta_leabra.dir/build
.PHONY : clean_ta_leabra/fast

#=============================================================================
# Target rules for targets named clean_ta_network

# Build rule for target.
clean_ta_network: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clean_ta_network
.PHONY : clean_ta_network

# fast build rule for target.
clean_ta_network/fast:
	$(MAKE) -f src/emergent/lib/CMakeFiles/clean_ta_network.dir/build.make src/emergent/lib/CMakeFiles/clean_ta_network.dir/build
.PHONY : clean_ta_network/fast

#=============================================================================
# Target rules for targets named clean_ta_so

# Build rule for target.
clean_ta_so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clean_ta_so
.PHONY : clean_ta_so

# fast build rule for target.
clean_ta_so/fast:
	$(MAKE) -f src/emergent/lib/CMakeFiles/clean_ta_so.dir/build.make src/emergent/lib/CMakeFiles/clean_ta_so.dir/build
.PHONY : clean_ta_so/fast

#=============================================================================
# Target rules for targets named emergentlib

# Build rule for target.
emergentlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 emergentlib
.PHONY : emergentlib

# fast build rule for target.
emergentlib/fast:
	$(MAKE) -f src/emergent/lib/CMakeFiles/emergentlib.dir/build.make src/emergent/lib/CMakeFiles/emergentlib.dir/build
.PHONY : emergentlib/fast

#=============================================================================
# Target rules for targets named emergent

# Build rule for target.
emergent: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 emergent
.PHONY : emergent

# fast build rule for target.
emergent/fast:
	$(MAKE) -f src/emergent/bin/CMakeFiles/emergent.dir/build.make src/emergent/bin/CMakeFiles/emergent.dir/build
.PHONY : emergent/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... ChangeLog"
	@echo "... Continuous"
	@echo "... ContinuousBuild"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousStart"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... Experimental"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalUpdate"
	@echo "... Nightly"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyMemCheck"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlySubmit"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... clean_plugins"
	@echo "... clean_system_plugins"
	@echo "... clean_ta_all"
	@echo "... clean_ta_emergent"
	@echo "... clean_user_plugins"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... plugins"
	@echo "... rebuild_cache"
	@echo "... svn_commit"
	@echo "... svn_update"
	@echo "... system_plugins"
	@echo "... test"
	@echo "... uninstall"
	@echo "... user_plugins"
	@echo "... make_mta_parse"
	@echo "... maketa"
	@echo "... make_ta_qrc"
	@echo "... make_css_parse"
	@echo "... clean_ta_ta"
	@echo "... svn_revision_header"
	@echo "... temt"
	@echo "... css"
	@echo "... make_actr_parse"
	@echo "... clean_ta_actr"
	@echo "... clean_ta_bp"
	@echo "... clean_ta_cs"
	@echo "... clean_ta_leabra"
	@echo "... clean_ta_network"
	@echo "... clean_ta_so"
	@echo "... emergentlib"
	@echo "... emergent"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

