#!/bin/sh
# Due to a bug in CheckInstall, we have to do this manually.
# It sucks. Hopefully they will fix it, otherwise we need
# to stop using CheckInstall.
ln -s /usr/local/lib/libpdp-4.0.so.0.0.0 /usr/local/lib/libpdp-4.0.so.0
ln -s /usr/local/lib/libtacss-4.0.so.0.0.0 /usr/local/lib/libtacss-4.0.so.0
ln -s /usr/local/lib/libSoQt.so.20.4.1 /usr/local/lib/libSoQt.so.20
ln -s /usr/local/libCoin.so.40.4.5 /usr/local/libCoin.so.40

