#!/bin/sh

# sets shell for this instance of PDP

CPU=LINIXdebug
PDPDIR=/usr/src/pdp++dev
PDP_GUI=QT
LD_LIBRARY_PATH=$PDPDIR/lib/$CPU:/usr/local/iv/i686/lib

export CPU PDPDIR PDP_GUI LD_LIBRARY_PATH


