#ifndef psg_TA_types_h
#define psg_TA_types_h 1

// File Automatically Generated by MakeTA
// DO NOT EDIT


class TypeDef;
extern void ta_Init_psg();

extern TypeDef TA_PSGPlugin;
extern TypeDef TA_PSGBase;
extern TypeDef TA_const_PSGBase;
extern TypeDef TA_const_PSGBase_ref;


#endif // psg_TA_types_h
