#!/bin/sh

cat > /usr/share/applications/Emergent.desktop <<Emergent
[Desktop Entry]
Exec=/usr/local/bin/emergent
GenericName=Neural Network Simulation Software
Icon=/usr/local/share/Emergent/images/Emergent_128x128.png
Name=Emergent
StartupNotify=true
Terminal=0
Type=Application
X-KDE-SubstituteUID=false
Emergent

dcop kded kbuildsycoca recreate

ln -s /usr/local/lib/libSoQt.so.20.4.1 /usr/local/lib/libSoQt.so.20
ln -s /usr/local/lib/libCoin.so.40.4.5 /usr/local/lib/libCoin.so.40
