################################################################################
#
# Build script for project
#
################################################################################

# Add source files here
EXECUTABLE	:= ./embench_cuda
# Cuda source files (compiled with cudacc)
CUFILES		:= embench_cuda.cu
# C/C++ source files (compiled with gcc / c++)
CCFILES		:= \
	main.cpp 

BINDIR	= ./

################################################################################
# Rules and targets

include ${CUDA_SDK}/common/common.mk
