#ifndef test_TA_insts_h
#define test_TA_insts_h 1

// File Automatically Generated by MakeTA
// DO NOT EDIT


#include "ta_type.h"
#include "test_maketa.h"
#include "test_TA_type.h"




#endif // test_TA_insts_h
