// Copyright, 1995-2005, Regents of the University of Colorado,
// Carnegie Mellon University, Princeton University.
//
// This file is part of TA/CSS
//
//   This library is free software; you can redistribute it and/or
//   modify it under the terms of the GNU Lesser General Public
//   License as published by the Free Software Foundation; either
//   version 2.1 of the License, or (at your option) any later version.
//   
//   This library is distributed in the hope that it will be useful,
//   but WITHOUT ANY WARRANTY; without even the implied warranty of
//   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
//   Lesser General Public License for more details.

#ifndef test_TA_types_h
#define test_TA_types_h 1

// File Automatically Generated by MakeTA
// DO NOT EDIT


class TypeDef;
extern void ta_Init_test();

extern TypeDef TA_void;
extern TypeDef TA_int;
extern TypeDef TA_short;
extern TypeDef TA_long;
extern TypeDef TA_char;
extern TypeDef TA_unsigned;
extern TypeDef TA_signed;
extern TypeDef TA_float;
extern TypeDef TA_double;
extern TypeDef TA_bool;
extern TypeDef TA_const;
extern TypeDef TA_enum;
extern TypeDef TA_struct;
extern TypeDef TA_union;
extern TypeDef TA_class;
extern TypeDef TA_template;
extern TypeDef TA_templ_inst;
extern TypeDef TA_ta_array;
extern TypeDef TA_taBase;
extern TypeDef TA_taRegFun;
extern TypeDef TA_TypeDef;
extern TypeDef TA_MemberDef;
extern TypeDef TA_MethodDef;
extern TypeDef TA_taString;
extern TypeDef TA_void_ptr;
extern TypeDef TA_MyClass;
extern TypeDef TA_MySubClass;


#endif // test_TA_types_h
