#ifndef TA_TA_TYPE_WRAPPER_H
#define TA_TA_TYPE_WRAPPER_H

// Bug 1424
// CMake's dependency scanner is really stupid -- it doesn't actually
// preprocess header files to determine dependencies, it just scans
// for #include lines.  Consequently, it thinks maketa depends on
// files like svnrev.h and ta_TA_type.h, when in fact it does not --
// there's no way it could depend on ta_TA_type.h, since that file is
// generated by maketa!
//
// The purpose of this file is to fool CMake's dependency scanner.
//
// Include the ta_TA_type.h header in a way that the compiler will
// understand what's going on, but CMake won't automatically create
// a dependency.  The CMakeLists.txt files set the property
// IMPLICIT_DEPENDS_INCLUDE_TRANSFORM for all targets except maketa,
// which of course doesn't need to include its own output.

#define CMAKE_DEPENDENCY_HACK(a) #a
#include CMAKE_DEPENDENCY_HACK(ta_TA_type.h)
#undef CMAKE_DEPENDENCY_HACK

#endif // TA_TA_TYPE_WRAPPER_H
