#ifndef psg_TA_insts_h
#define psg_TA_insts_h 1

// File Automatically Generated by MakeTA
// DO NOT EDIT


#include "ta_type.h"
#include "psg.h"
#include "psg_TA_type.h"


extern PSGBase*	TAI_PSGBase;
extern PSGDemo*	TAI_PSGDemo;
extern PSGArm*	TAI_PSGArm;


#endif // psg_TA_insts_h
