#ifndef leabra_TA_insts_h
#define leabra_TA_insts_h 1

// File Automatically Generated by MakeTA
// DO NOT EDIT


#include "ta_type.h"
#include "ta_TA_type.h"
#include "tamisc_TA_type.h"
#include "pdp_TA_type.h"
#include "leabra.h"
#include "leabra_TA_type.h"


extern	LeabraCon*	TAI_LeabraCon;
extern	LeabraConSpec*	TAI_LeabraConSpec;
extern	LeabraBiasSpec*	TAI_LeabraBiasSpec;
extern	LeabraCon_Group*	TAI_LeabraCon_Group;
extern	LeabraUnitSpec*	TAI_LeabraUnitSpec;
extern	LeabraUnit*	TAI_LeabraUnit;
extern	LeabraInhib*	TAI_LeabraInhib;
extern	LeabraLayerSpec*	TAI_LeabraLayerSpec;
extern	LeabraUnit_Group*	TAI_LeabraUnit_Group;
extern	LeabraLayer*	TAI_LeabraLayer;
extern	LeabraCycle*	TAI_LeabraCycle;
extern	LeabraSettle*	TAI_LeabraSettle;
extern	LeabraTrial*	TAI_LeabraTrial;
extern	LeabraMaxDa*	TAI_LeabraMaxDa;
extern	WtScaleSpec*	TAI_WtScaleSpec;
extern	WtSigSpec*	TAI_WtSigSpec;
extern	LearnMixSpec*	TAI_LearnMixSpec;
extern	SAvgCorSpec*	TAI_SAvgCorSpec;
extern	ActFunSpec*	TAI_ActFunSpec;
extern	SpikeFunSpec*	TAI_SpikeFunSpec;
extern	DepressSpec*	TAI_DepressSpec;
extern	OptThreshSpec*	TAI_OptThreshSpec;
extern	DtSpec*	TAI_DtSpec;
extern	LeabraChannels*	TAI_LeabraChannels;
extern	VChanSpec*	TAI_VChanSpec;
extern	ActRegSpec*	TAI_ActRegSpec;
extern	VChanBasis*	TAI_VChanBasis;
extern	LeabraUnitChans*	TAI_LeabraUnitChans;
extern	taPtrList<LeabraUnit>*	TAI_taPtrList_LeabraUnit_;
extern	LeabraSort*	TAI_LeabraSort;
extern	KWTASpec*	TAI_KWTASpec;
extern	AdaptISpec*	TAI_AdaptISpec;
extern	ClampSpec*	TAI_ClampSpec;
extern	DecaySpec*	TAI_DecaySpec;
extern	SpecPtr<LeabraLayerSpec>*	TAI_SpecPtr_LeabraLayerSpec_;
extern	LeabraLayerSpec_SPtr*	TAI_LeabraLayerSpec_SPtr;
extern	AvgMaxVals*	TAI_AvgMaxVals;
extern	KWTAVals*	TAI_KWTAVals;
extern	AdaptIVals*	TAI_AdaptIVals;
extern	InhibVals*	TAI_InhibVals;
extern	LeabraSE_Stat*	TAI_LeabraSE_Stat;
extern	LeabraGoodStat*	TAI_LeabraGoodStat;
extern	LeabraSharpStat*	TAI_LeabraSharpStat;
extern	WrongOnStat*	TAI_WrongOnStat;
extern	LeabraPrjnRelNetinStat*	TAI_LeabraPrjnRelNetinStat;
extern	CtxtUpdateSpec*	TAI_CtxtUpdateSpec;
extern	LeabraContextLayerSpec*	TAI_LeabraContextLayerSpec;
extern	PhaseOrderEventSpec*	TAI_PhaseOrderEventSpec;
extern	LeabraLinUnitSpec*	TAI_LeabraLinUnitSpec;
extern	LeabraNegBiasSpec*	TAI_LeabraNegBiasSpec;
extern	TrialSynDepCon*	TAI_TrialSynDepCon;
extern	SynDepSpec*	TAI_SynDepSpec;
extern	TrialSynDepConSpec*	TAI_TrialSynDepConSpec;
extern	FastWtCon*	TAI_FastWtCon;
extern	FastWtSpec*	TAI_FastWtSpec;
extern	FastWtConSpec*	TAI_FastWtConSpec;
extern	ScalarValSpec*	TAI_ScalarValSpec;
extern	ScalarValBias*	TAI_ScalarValBias;
extern	ScalarValLayerSpec*	TAI_ScalarValLayerSpec;
extern	ScalarValSelfPrjnSpec*	TAI_ScalarValSelfPrjnSpec;
extern	TwoDValSpec*	TAI_TwoDValSpec;
extern	TwoDValBias*	TAI_TwoDValBias;
extern	TwoDValLayerSpec*	TAI_TwoDValLayerSpec;
extern	MarkerConSpec*	TAI_MarkerConSpec;
extern	DaModUnit*	TAI_DaModUnit;
extern	DaModSpec*	TAI_DaModSpec;
extern	DaModUnitSpec*	TAI_DaModUnitSpec;
extern	AvgExtRewSpec*	TAI_AvgExtRewSpec;
extern	OutErrSpec*	TAI_OutErrSpec;
extern	ExtRewSpec*	TAI_ExtRewSpec;
extern	ExtRewLayerSpec*	TAI_ExtRewLayerSpec;
extern	ExtRew_Stat*	TAI_ExtRew_Stat;
extern	TDRewPredConSpec*	TAI_TDRewPredConSpec;
extern	TDRewPredLayerSpec*	TAI_TDRewPredLayerSpec;
extern	TDRewIntegSpec*	TAI_TDRewIntegSpec;
extern	TDRewIntegLayerSpec*	TAI_TDRewIntegLayerSpec;
extern	TdLayerSpec*	TAI_TdLayerSpec;
extern	PVConSpec*	TAI_PVConSpec;
extern	PVDetectSpec*	TAI_PVDetectSpec;
extern	PViLayerSpec*	TAI_PViLayerSpec;
extern	LVConSpec*	TAI_LVConSpec;
extern	LVSpec*	TAI_LVSpec;
extern	LVeLayerSpec*	TAI_LVeLayerSpec;
extern	LViLayerSpec*	TAI_LViLayerSpec;
extern	PVLVDaSpec*	TAI_PVLVDaSpec;
extern	PVLVDaLayerSpec*	TAI_PVLVDaLayerSpec;
extern	PatchLayerSpec*	TAI_PatchLayerSpec;
extern	SNcMiscSpec*	TAI_SNcMiscSpec;
extern	SNcLayerSpec*	TAI_SNcLayerSpec;
extern	MatrixConSpec*	TAI_MatrixConSpec;
extern	MatrixBiasSpec*	TAI_MatrixBiasSpec;
extern	MatrixUnitSpec*	TAI_MatrixUnitSpec;
extern	ContrastSpec*	TAI_ContrastSpec;
extern	MatrixRndGoSpec*	TAI_MatrixRndGoSpec;
extern	MatrixRndGoThrSpec*	TAI_MatrixRndGoThrSpec;
extern	MatrixMiscSpec*	TAI_MatrixMiscSpec;
extern	MatrixLayerSpec*	TAI_MatrixLayerSpec;
extern	SNrThalLayerSpec*	TAI_SNrThalLayerSpec;
extern	PFCGateSpec*	TAI_PFCGateSpec;
extern	PFCLayerSpec*	TAI_PFCLayerSpec;
extern	LeabraWiz*	TAI_LeabraWiz;


#endif // leabra_TA_insts_h
