#!/bin/bash
set -e

#sudo apt-get install build-essential gnupg lintian fakeroot debhelper dh-make subversion-tools devscripts mercurial

echo "Building Quarter from Mercurial source"

QUARTER_VERSION=1.0
DEBEMAIL='brian.mingus@colorado.edu'
DEBFULLNAME='Brian Mingus'
REPONAME=`lsb_release -cs` # e.g., "maverick"

QUARTER_BLD_DIR=libquarter0-${QUARTER_VERSION}
QUARTER_BLD_PATH=/tmp/${QUARTER_BLD_DIR}
rm -fr ${QUARTER_BLD_PATH}
hg clone http://hg.sim.no/Quarter/default ${QUARTER_BLD_PATH}
# r460 is the last rev of Quarter to compile with libcoin60-dev (3.1.x)
cd ${QUARTER_BLD_PATH}
hg update -r 460
cd /tmp
tar -czf libquarter0_${QUARTER_VERSION}.orig.tar.gz ${QUARTER_BLD_DIR}
cd ${QUARTER_BLD_DIR}
mkdir -p debian

#################################################
# Create debian/changelog
#################################################
cat > debian/changelog <<Quarter
libquarter0 (1.0-0ubuntu1) ${REPONAME}; urgency=low

  * Initial release (LP: #364748)

 -- ${DEBFULLNAME} <${DEBEMAIL}>  $(date -R)
Quarter

#################################################
# Create debian/control
#################################################
cat > debian/control <<Quarter
Source: libquarter0
Section: graphics
Priority: extra
Maintainer: Ubuntu MOTU Developers <ubuntu-motu@lists.ubuntu.com>
XSBC-Original-Maintainer: ${DEBFULLNAME} <${DEBEMAIL}>
Build-Depends: debhelper (>= 7.0.17), libqt4-dev, libqt4-opengl-dev, libqt4-designer, libcoin60-dev, pkg-config
Standards-Version: 3.9.1

Homepage: http://www.coin3d.org/lib/quarter
Package: libquarter0
Architecture: any
Depends: \${shlibs:Depends}, \${misc:Depends}
Description: Glue between Coin3D and Qt
 A light-weight glue library that provides seamless integration 
 between Kongsberg SIM's Coin high-level 3D visualization library and
 Nokia's Qt 2D user interface library.

Quarter

#################################################
# Create debian/copyright
#################################################
cat > debian/copyright <<Quarter

This package was debianized by:

    ${DEBFULLNAME} <${DEBEMAIL}> on $(date -R)

It was downloaded from:

    http://www.coin3d.org/lib/quarter

Upstream Author:

    Coin3D <help@coin3d.org>

Copyright:

     Copyright 1998-2009 by Systems in Motion. 

License:

     This file is part of the SIM Quarter extension library for Coin.
 
     Quarter is free software; you can redistribute it and/or modify
     it under the terms of the GNU General Public License as published by
     the Free Software Foundation; either version 2 of the License, or
     (at your option) any later version.

     Quarter is distributed in the hope that it will be useful,
     but WITHOUT ANY WARRANTY; without even the implied warranty of
     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
     GNU General Public License for more details.

     You should have received a copy of the GNU General Public License
     along with this package; if not, write to the Free Software
     Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA

The Debian packaging is:

    Copyright 2009, ${DEBFULLNAME} <${DEBEMAIL}>

and is licensed under the GPL, see above.

X-Comment: On Debian GNU/Linux systems, the complete text of the GNU General
 Public License can be found in the /usr/share/common-licenses/GPL-2 file.

Quarter

#################################################
# debian/rules makefile
#################################################
cat > debian/rules <<Quarter
#!/usr/bin/make -f

build: build-stamp
build-stamp:
	dh build
	touch build-stamp

clean:
	dh clean

install: build install-stamp
install-stamp:
	dh install
	touch install-stamp

binary-arch: install
	dh binary-arch

binary-indep: install
	dh binary-indep

binary: binary-arch binary-indep
Quarter

#################################################
# debian/compat 
#################################################
cat > debian/compat <<Quarter
7
Quarter

#debuild -S -us -uc
debuild -i -b -us -uc

