// This file has been generated by Py++.

#include "boost/python.hpp"

#include "ta_gendoc.h"

namespace bp = boost::python;

BOOST_PYTHON_MODULE(PyEmergent){
  bp::class_< taGenDoc, boost::noncopyable >( "taGenDoc", bp::no_init )    
    .def( 
	 "GenDoc"
	 , (void (*)( ::TypeSpace *,::std::fstream & ))( &::taGenDoc::GenDoc )
	 , ( bp::arg("ths"), bp::arg("strm") ) )    
    .def( 
	 "MemberSpace_Filter_Member"
	 , (bool (*)( ::MemberSpace *,::MemberDef * ))( &::taGenDoc::MemberSpace_Filter_Member )
	 , ( bp::arg("ths"), bp::arg("md") ) )    
    .def( 
	 "MethodSpace_Filter_Method"
	 , (bool (*)( ::MethodSpace *,::MethodDef * ))( &::taGenDoc::MethodSpace_Filter_Method )
	 , ( bp::arg("ths"), bp::arg("md") ) )    
    .def( 
	 "TypeDef_Filter_Type"
	 , (bool (*)( ::TypeDef *,::TypeSpace * ))( &::taGenDoc::TypeDef_Filter_Type )
	 , ( bp::arg("td"), bp::arg("ts") ) )    
    .staticmethod( "GenDoc" )    
    .staticmethod( "MemberSpace_Filter_Member" )    
    .staticmethod( "MethodSpace_Filter_Method" )    
    .staticmethod( "TypeDef_Filter_Type" );
}
